name: ETL Pipeline

# When this workflow runs:
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"   # every day at 2:00 AM UTC
  workflow_dispatch:        # lets you click "Run workflow" manually on GitHub

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Run ETL pipeline
        run: python src/main.py
