name: MY ETL Pipeline

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:

      # 1. Download the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Run tests
      - name: Run tests
        run: pytest

      # 5. Run ETL pipeline
      - name: Run ETL pipeline
        run: python src/main.py

      # 6. Check database file
      - name: Show the database file exists
        run: ls -lh etl.db

      # 7. Check whether extract.py changed
      - name: Check if extract.py changed
        id: check_extract
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^src/extract.py$'; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "extract.py was changed."
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "extract.py was not changed."
          fi

      # 8. Delete demo.txt if extract.py changed
      - name: Delete demo.txt if extract.py changed
        if: steps.check_extract.outputs.changed == 'true'
        run: |
          if [ -f demo.txt ]; then
            echo "extract.py changed. Deleting demo.txt..."

            rm demo.txt

            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add demo.txt
            git commit -m "Delete demo.txt because extract.py changed"

            git push

            echo "demo.txt deleted successfully."
          else
            echo "demo.txt does not exist."
          fi
